Download directly into the bin directory.

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -10,7 +10,7 @@ fail() {
 install_mint() {
   local install_type=$1
   local version=$2
-  local install_path=$3
+  local install_path="${3}/bin"
 
   if [ "$install_type" != "version" ]; then
     fail "asdf-mint supports release installs only"
@@ -32,15 +32,10 @@ install_mint() {
   esac
 
   local download_url="https://github.com/mint-lang/mint/releases/download/${version}/mint-${version}-${platform}"
-  local tmp_download_dir
-  tmp_download_dir=$(mktemp -d -t mint_tmp_XXXXXX)
-  local source_path="${tmp_download_dir}/mint"
 
   (
     echo "∗ Downloading and installing mint..."
-    curl --silent --fail --location --create-dirs --output "$source_path" "$download_url" || fail "Could not download mint $version"
-    mv "$source_path" "$install_path"
-    rm -rf "$tmp_download_dir"
+    curl --silent --fail --location --create-dirs --output "$distination_path" "$install_path" || fail "Could not download mint $version"
     echo "The installation was successful!"
   ) || (
     rm -rf "$install_path"
