Update install script so it works.

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -10,7 +10,7 @@ fail() {
 install_mint() {
   local install_type=$1
   local version=$2
-  local install_path="${3}/bin"
+  local install_path=$3
 
   if [ "$install_type" != "version" ]; then
     fail "asdf-mint supports release installs only"
@@ -24,18 +24,11 @@ install_mint() {
     *) fail "Unsupported platform" ;;
   esac
 
-  local architecture
-
-  case "$(uname -m)" in
-    x86_64) architecture="x86_64" ;;
-    *) fail "Unsupported architecture" ;;
-  esac
-
   local download_url="https://github.com/mint-lang/mint/releases/download/${version}/mint-${version}-${platform}"
 
   (
     echo "∗ Downloading and installing mint..."
-    curl --silent --fail --location --create-dirs --output "$distination_path" "$install_path" || fail "Could not download mint $version"
+    curl --silent --fail --location --create-dirs --output "$install_path/bin/mint" "$download_url" || fail "Could not download mint $version"
     echo "The installation was successful!"
   ) || (
     rm -rf "$install_path"
